{
 "title": "Flotte Solo-Corsair",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Trafic / Requêtes par seconde",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latence & Performance sur /travail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket{path=\"/travail\"}[1m])) by (le, job))",
     "legendFormat": "p95 {{job}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(flask_http_request_duration_seconds_bucket{path=\"/travail\"}[1m])) by (le, job))",
     "legendFormat": "p50 {{job}}"
    }
   ]
  },
  {
   "title": "Santé des Dépendances (BDD)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sante_bdd", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Versions par instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "service_version" }
   ]
  }
 ]
}